test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,7 +15,7 @@ name: Release
 
 on:
   push:
-    branches: ["initial_dev"]
+    branches: ["aarch64_action_tests"]
   release:
     types: [published]
   schedule:
@@ -96,42 +96,42 @@ jobs:
       fail-fast: false
       matrix:
         job:
-          - { target: x86_64-unknown-linux-gnu, arch: amd64, os: ubuntu-20.04 }
+          - { target: x86_64-unknown-linux-gnu, arch: amd64, os: ubuntu-latest }
           - { target: x86_64-apple-darwin, arch: darwin, os: macos-latest }
           - {
               target: x86_64-unknown-linux-musl,
               arch: amd64,
-              os: ubuntu-20.04,
+              os: ubuntu-latest,
               use-cross: true,
             }
-          # - {
-          #     target: arm-unknown-linux-gnueabi,
-          #     arch: armel,
-          #     os: ubuntu-20.04,
-          #     use-cross: true,
-          #   }
-          # - {
-          #     target: arm-unknown-linux-gnueabihf,
-          #     arch: armhf,
-          #     os: ubuntu-20.04,
-          #     use-cross: true,
-          #   }
-          # - {
-          #     target: armv7-unknown-linux-gnueabihf,
-          #     arch: armhf,
-          #     os: ubuntu-20.04,
-          #     use-cross: true,
-          #   }
+          - {
+              target: arm-unknown-linux-gnueabi,
+              arch: armel,
+              os: ubuntu-latest,
+              use-cross: true,
+            }
+          - {
+              target: arm-unknown-linux-gnueabihf,
+              arch: armhf,
+              os: ubuntu-latest,
+              use-cross: true,
+            }
+          - {
+              target: armv7-unknown-linux-gnueabihf,
+              arch: armhf,
+              os: ubuntu-latest,
+              use-cross: true,
+            }
           - {
               target: aarch64-unknown-linux-gnu,
               arch: arm64,
-              os: ubuntu-20.04,
+              os: ubuntu-latest,
               use-cross: true,
             }
           - {
               target: aarch64-unknown-linux-musl,
               arch: arm64,
-              os: ubuntu-20.04,
+              os: ubuntu-latest,
               use-cross: true,
             }
           ##
@@ -265,85 +265,85 @@ jobs:
             ${{ steps.package.outputs.BIN_PKG_NAME }}
             ${{ steps.package.outputs.DEBS_PKG_NAME }}
 
-  docker-build:
-    name: Docker build and push
-    needs: [checks, builds]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 500 # NOTE: get long history for git-version crate to correctly compute a version
-      - name: Fetch Git tags # NOTE: workaround for https://github.com/actions/checkout/issues/290
-        shell: bash
-        run: git fetch --tags --force
-      - name: Download packages from previous job
-        uses: actions/download-artifact@v2
-        with:
-          path: PACKAGES
-      - name: Unzip PACKAGES
-        run: |
-          ls PACKAGES
-          mkdir -p docker/linux/amd
-          unzip PACKAGES/x86_64-unknown-linux-musl/zenoh-bridge-mqtt-${{ needs.checks.outputs.PKG_VERSION }}-x86_64-unknown-linux-musl.zip -d docker/linux/amd64/
-          mkdir -p docker/linux/arm64
-          unzip PACKAGES/aarch64-unknown-linux-musl/zenoh-bridge-mqtt-${{ needs.checks.outputs.PKG_VERSION }}-aarch64-unknown-linux-musl.zip -d docker/linux/arm64/
-          tree docker
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Docker meta - set tags and labels
-        id: meta
-        uses: docker/metadata-action@v3
-        with:
-          images: eclipse/zenoh-bridge-mqtt
-      - name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKER_COM_USERNAME }}
-          password: ${{ secrets.DOCKER_COM_PASSWORD }}
-      - name: Build and push
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          platforms: linux/amd64,linux/arm64
-          file: .github/workflows/Dockerfile
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+  # docker-build:
+  #   name: Docker build and push
+  #   needs: [checks, builds]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 500 # NOTE: get long history for git-version crate to correctly compute a version
+  #     - name: Fetch Git tags # NOTE: workaround for https://github.com/actions/checkout/issues/290
+  #       shell: bash
+  #       run: git fetch --tags --force
+  #     - name: Download packages from previous job
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         path: PACKAGES
+  #     - name: Unzip PACKAGES
+  #       run: |
+  #         ls PACKAGES
+  #         mkdir -p docker/linux/amd
+  #         unzip PACKAGES/x86_64-unknown-linux-musl/zenoh-bridge-mqtt-${{ needs.checks.outputs.PKG_VERSION }}-x86_64-unknown-linux-musl.zip -d docker/linux/amd64/
+  #         mkdir -p docker/linux/arm64
+  #         unzip PACKAGES/aarch64-unknown-linux-musl/zenoh-bridge-mqtt-${{ needs.checks.outputs.PKG_VERSION }}-aarch64-unknown-linux-musl.zip -d docker/linux/arm64/
+  #         tree docker
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
+  #     - name: Docker meta - set tags and labels
+  #       id: meta
+  #       uses: docker/metadata-action@v3
+  #       with:
+  #         images: eclipse/zenoh-bridge-mqtt
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKER_COM_USERNAME }}
+  #         password: ${{ secrets.DOCKER_COM_PASSWORD }}
+  #     - name: Build and push
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         context: .
+  #         platforms: linux/amd64,linux/arm64
+  #         file: .github/workflows/Dockerfile
+  #         push: true
+  #         tags: ${{ steps.meta.outputs.tags }}
+  #         labels: ${{ steps.meta.outputs.labels }}
 
-  publication:
-    name: Release publication
-    if: needs.checks.outputs.IS_RELEASE == 'true'
-    needs: [checks, builds]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download result of previous builds
-        uses: actions/download-artifact@v2
-        with:
-          path: ARTIFACTS
-      - name: Publish as github release
-        uses: softprops/action-gh-release@v1
-        with:
-          files: ARTIFACTS/*/*.*
-      - name: Publish to download.eclipse.org/zenoh
-        env:
-          SSH_TARGET: genie.zenoh@projects-storage.eclipse.org
-          ECLIPSE_BASE_DIR: /home/data/httpd/download.eclipse.org/zenoh/zenoh-plugin-mqtt
-        shell: bash
-        run: |
-          echo "--- setup ssh-agent"
-          eval "$(ssh-agent -s)"
-          echo 'echo "${{ secrets.SSH_PASSPHRASE }}"' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | DISPLAY=NONE SSH_ASKPASS=~/.ssh_askpass ssh-add - > /dev/null 2>&1
-          rm -f ~/.ssh_askpass
-          echo "--- test ssh:"
-          ssh -o "StrictHostKeyChecking=no" ${SSH_TARGET} ls -al
-          echo "---- list artifacts to upload:"
-          ls -R ARTIFACTS || true
-          DOWNLOAD_DIR=${ECLIPSE_BASE_DIR}/${{ needs.checks.outputs.ZENOH_VERSION }}
-          echo "---- copy artifacts into ${DOWNLOAD_DIR}"
-          ssh -o "StrictHostKeyChecking=no" ${SSH_TARGET} mkdir -p ${DOWNLOAD_DIR}
-          cd ARTIFACTS
-          sha256sum */* > sha256sums.txt
-          scp -o "StrictHostKeyChecking=no" -r * ${SSH_TARGET}:${DOWNLOAD_DIR}/
-          echo "---- cleanup identity"
-          ssh-add -D
+  # publication:
+  #   name: Release publication
+  #   if: needs.checks.outputs.IS_RELEASE == 'true'
+  #   needs: [checks, builds]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Download result of previous builds
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         path: ARTIFACTS
+  #     - name: Publish as github release
+  #       uses: softprops/action-gh-release@v1
+  #       with:
+  #         files: ARTIFACTS/*/*.*
+  #     - name: Publish to download.eclipse.org/zenoh
+  #       env:
+  #         SSH_TARGET: genie.zenoh@projects-storage.eclipse.org
+  #         ECLIPSE_BASE_DIR: /home/data/httpd/download.eclipse.org/zenoh/zenoh-plugin-mqtt
+  #       shell: bash
+  #       run: |
+  #         echo "--- setup ssh-agent"
+  #         eval "$(ssh-agent -s)"
+  #         echo 'echo "${{ secrets.SSH_PASSPHRASE }}"' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
+  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | DISPLAY=NONE SSH_ASKPASS=~/.ssh_askpass ssh-add - > /dev/null 2>&1
+  #         rm -f ~/.ssh_askpass
+  #         echo "--- test ssh:"
+  #         ssh -o "StrictHostKeyChecking=no" ${SSH_TARGET} ls -al
+  #         echo "---- list artifacts to upload:"
+  #         ls -R ARTIFACTS || true
+  #         DOWNLOAD_DIR=${ECLIPSE_BASE_DIR}/${{ needs.checks.outputs.ZENOH_VERSION }}
+  #         echo "---- copy artifacts into ${DOWNLOAD_DIR}"
+  #         ssh -o "StrictHostKeyChecking=no" ${SSH_TARGET} mkdir -p ${DOWNLOAD_DIR}
+  #         cd ARTIFACTS
+  #         sha256sum */* > sha256sums.txt
+  #         scp -o "StrictHostKeyChecking=no" -r * ${SSH_TARGET}:${DOWNLOAD_DIR}/
+  #         echo "---- cleanup identity"
+  #         ssh-add -D
